name: $(Date:yyyyMMdd).$(Rev:.r)
variables:
  - group: Polaris
  project: 'chuckaude-hello-java'

jobs:
- job: Polaris
  pool:
    name: private-windows
  workspace:
    clean: all
  steps:
  - task: CmdLine@2
    displayName: setup
    inputs:
      script: '$(polaris_cmd) setup --project-name $(project) -e shell="mvn clean" -b shell="mvn package -DskipTests"'
  - task: CmdLine@2
    displayName: analyze
    inputs:
      script: '$(polaris_cmd) analyze -w'
