Name: 'AEP Action: Black Duck Detect Scan'
description: 'Standard AEP Action Perform an SCA scan for your Project with Synopsys Black Duck Detect'
author: 'Mark Ritchey'

inputs:
  Blackduck_API_Token:
    description: Black Duck API Token for Application
    required: true
  GitHub_Token:
    description: Black Duck API Token for Application
    required: true
  Blackduck_URL: 
    description: URL for Code Dx
    required: false
    default: 'https://poc312.blackduck.synopsys.com'
    # default: 'https://blackduck-test.aepsc.com'
  Detect_Scan_Mode:
    description: 'The Type of Scan to Perform within Black Duck (INTELLIGENT or RAPID)'
    required: false
    default: 'INTELLIGENT'
  Detect_Code_Loc_Name:
    description: 'The Name of the Scan ID/Name within Black Duck'
    required: false
    default: '${{github.event.repository.name}}-${{github.ref_name}}-${{ github.run_number }}'
  Detect_Excluded_Directories:
    description: 'The Name of the directories to exclude from your Black Duck Scan'
    required: false
    default: 'idir'

runs:
# ----------- Composite required for Action Definition-------------
  using: 'composite'

  steps:           
    - name: Run Synopsys Black Duck Detect
      # uses: aep-actions/synopsys-action@main
      uses: synopsys-sig/synopsys-action@v1.9.0
      env:
        # NODE_EXTRA_CA_CERTS: ${{env.AEP_CERT}}  #used by AEP but not required for prototyping environment
        DETECT_PROJECT_NAME: ${{github.event.repository.name}}
        DETECT_PROJECT_VERSION_NAME: ${{github.ref_name}}
        DETECT_CODE_LOCATION_NAME: ${{inputs.Detect_Code_Loc_Name}}
        DETECT_EXCLUDED_DIRECTORIES: ${{inputs.Detect_Excluded_Directories}}
      with:
        ### SCANNING: Required fields
        blackduck_url: ${{ inputs.Blackduck_URL }}
        blackduck_token: ${{ inputs.Blackduck_API_Token }}
        blackduck_scan_full: true
        ### SCANNING: Optional fields
        # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
        ### FIX PULL REQUEST CREATION: Uncomment below to enable
        # blackduck_fixpr_enabled: true
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
        ### PULL REQUEST COMMENTS: Uncomment below to enable
        # blackduck_prcomment_enabled: true 
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled
        ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
        # blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
        # blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true
