Name: 'AEP Action: Coverity Build/Scan - new'
description: 'Standard AEP Action for Performing a Coverity Build/Scan'
author: 'Mark Ritchey'

inputs:
  #-  #---- Coverity Inputs ------------
  Coverity_Username:
    type: string
    description: 'Coverity Connect Username'
    required: true
  Coverity_Password:
    type: string
    description: 'Coverity Connect Username'
    required: true
  Coverity_URL:
    type: string
    description: ''
    required: false
    default: 'https://poc312.coverity.synopsys.com'
    # default: 'https://coverity-test.aepsc.com/'
  Coverity_Checkers:
    type: string
    description: 'List of all Coverity Checkers and Aggressiveness Levels (Default: all)'
    required: false
    default: '--all'

runs:
# ----------- Composite required for Action Definition-------------
  using: 'composite'
  
  steps: 
    - name: Coverity Build Scan
      uses: synopsys-sig/synopsys-action@v1.9.0
      with:
        ### SCANNING: Required fields
        coverity_url: ${{ inputs.Coverity_URL }}
        coverity_user: ${{ inputs.Coverity_Username }}
        coverity_passphrase: ${{ inputs.Coverity_Password }}
        coverity_project_name: '${{ github.event.repository.name }}'
        coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
        # coverity_stream_name: '${{ github.event.repository.name }}(${{ github.ref_name }})' ## SLS replaced with line above
        ### Coverity Connect users - Uncomment below
        # coverity_local: true ### SLS - commented out this line
        # coverity_install_directory: '/home/ghrunner/Coverity' ### SLS - commented out this line
        #coverity_install_directory: 'C:\Program Files\Coverity\Coverity Static Analysis\'
        
        ### POLICY ENFORCEMENT: Uncomment to break build on policy
        # coverity_policy_view: 'Outstanding Issues' 
        
        ### PULL REQUEST COMMENTS: Uncomment below to enable
        # coverity_prComment_enabled: true
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled  
          