# Polaris on a self-hosted runner
name: polaris

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: self-hosted

    env:
      POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}

    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      run: |
        /opt/polaris/bin/polaris --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w
