name: Polaris private runner
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  polaris:

    runs-on: self-hosted

    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: hello-java
      BLDCMD: mvn -B package -DskipTests

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Polaris Scan
      run: |
        /opt/polaris/bin/polaris setup -p chuckaude-hello-java -e shell='mvn -B clean' -b shell='mvn -B package -DskipTests'
        /opt/polaris/bin/polaris analyze -w
