# Polaris on a GitHub-hosted ephemeral runner inside a docker image
name: polaris-ephemeral-docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest
    container:
      image: maven:3-jdk-11

    env:
      POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Polaris Scan
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d $RUNNER_TEMP -jo polaris_cli-linux64.zip
        $RUNNER_TEMP/polaris --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w
