# example workflow for standalone Black Duck, Coverity and SRM (Code DX) using GitHub Actions
# - Black Duck and Coverity full scans on push to specified branches with upload to SRM
# - Black Duck RAPID and Coverity Comparison scans on pull requests with PR comments enabled
# - 2024-04-24 - added "- name: clean git > run: rm -r .git/config" to workflow to prevent issues with uploads to BD
#
# https://github.com/marketplace/actions/synopsys-action
# https://github.com/marketplace/actions/code-dx-analysis
#
#
#  ENVIRONMENT VARIABLES AND SECRETS 
# vars.BLACKDUCK_URL
# secrets.BLACKDUCK_API_TOKEN
# vars.COVERITY_URL
# secrets.COV_USER
# secrets.COVERITY_PASSPHRASE
# vars.SRM_URL
# secrets.SRM_APIKEY
# secrets.GITHUB_TOKEN  #  Confirm GITHUB_TOKEN has workflow read & write permissions (GitHub → Project → Settings → Actions → General → Workflow Permissions)
# 
# change to force github action PR for 1-samshober-patch 2024-05-28 10.02 am 
#
name: SRM-create new branch
on:
  push:
    branches:
    - "*"
    # branches: [ main, 1-SamShoberWork-patch, 2-Feature-Branch, 3-Release-Branch, 4-Dev, 5-Testing, 6-Production, StreamNameAAA ]
  pull_request:
    branches: [ main, 1-SamShoberWork-patch ]
  workflow_dispatch:
jobs:
  SRM-Branch:
    runs-on: ubuntu-latest
    steps:
    - name: SRM Upload
      if: ${{ github.event_name != 'pull_request' }}
      if: ${{ github.event.repository.default_branch = '3-Release-Branch' }} 
      uses: 'codedx/codedx-github-action@v1.2.0'
      with:
        server-url: ${{ vars.SRM_URL }}/srm
        api-key: ${{ secrets.SRM_APIKEY }}
        # ER CDX-1693 support project-name
        project-name: ${{ github.event.repository.name }}
        # project-id: "4;branch=${{ github.ref_name }}"  
        # ER CDX-1666 support branch-name
        base-branch-name: ${{ github.event.repository.default_branch }}
        target-branch-name: 'Dev auto created by SRM action'
        # target-branch-name: ${{ github.ref_name }}   
        source-and-binaries-glob: './**'
        wait-for-completion: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
