pool:
  name: 'private-windows'

variables:
- group: coverity-onprem
- name: COVERITY_TOOL_HOME
  value: $(COVERITY_TOOL_HOME_Windows_NT)

workspace:
  clean: all

steps:
- task: synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1
  displayName: 'Coverity'
  inputs:
    coverityService: 'coverity-onprem'
    projectName: '$(COV_PROJECT)'
    streamName: '$(COV_PROJECT)-$(Build.SourceBranchName)'
    checkIssues: true
    issueView: 'Outstanding Issues'
    issueStatus: success
    buildCommand: 'mvn -B package -DskipTests'
    customCommandArgs: true
    covBuildArgs: '--fs-capture-search $(Build.SourcesDirectory)'
    covAnalyzeArgs: '--ticker-mode none --strip-path $(Build.SourcesDirectory) --webapp-security'
    covCommitArgs: '--ticker-mode none --description $(Build.BuildURI) --version $(Build.SourceVersion) --scm git'
    allowUntrusted: true
