variables:
  - group: Polaris
  - name: project
    value: 'chuckaude-hello-java'

jobs:
- job: Polaris
  pool:
    vmImage: vs2017-win2016
  workspace:
    clean: all
  steps:
  - task: synopsys-polaris.synopsys-polaris.synopsys-polaris-task.SynopsysPolaris@1
    displayName: 'Synopsys Polaris'
    inputs:
      polarisService: 'polaris-sipse'
      polarisCommand: '--co project.name=$(project) analyze -w -- mvn -B package -DskipTests'
