variables:
  - group: Polaris
  - name: project
    value: 'chuckaude-hello-java'

jobs:
- job: Polaris
  pool:
    vmImage: vs2017-win2016
  workspace:
    clean: all
  steps:
  - task: CmdLine@2
    displayName: Polaris
    inputs:
      script: |
        curl -fsLOS %POLARIS_SERVER_URL%/api/tools/polaris_cli-win64.zip
        unzip -d /tmp -jo polaris_cli-win64.zip
        /tmp/polaris setup --project-name $(project) -e shell="mvn -B clean" -b shell="mvn -B package -DskipTests"
        /tmp/polaris analyze -w'
